// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oajaurcaaahuvmrcsuut.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9hamF1cmNhYWFodXZtcmNzdXV0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxNjU2MTYsImV4cCI6MjA2NDc0MTYxNn0.0ZKr2obuwITaL9g5LSf1N5LzF03hwmihFyuEXl16AT8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);